[package]
authors = ["Dev Random <c1.devrandom@niftybox.net>"]
edition = "2018"
readme = "README.md"
name = "embedded"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"
alloc-cortex-m = "0.4.1"

lightning-signer-core = { path="../lightning-signer-core", default-features = false, features = ["no-std"] }

[dependencies.bitcoin]
version = "0.27"
features = ["no-std", "secp-lowmemory"]
default-features = false

[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "4c4d99b291c5336130d3d5cfeffa8ab88fd97783"
version = "0.0.100"
default-features = false

[patch.crates-io]
# See also https://github.com/rust-bitcoin/rust-secp256k1/pull/299 and https://github.com/bitcoin-core/secp256k1/pull/956

# Uncomment this line to use a low-memory version of secp256k1 with static precomputation
#secp256k1 = { git = "https://github.com/devrandom/rust-secp256k1.git", rev = "4e745ebe7e4c9cd0a7e9c8d5c42e989522e52f71" }

[[bin]]
name = "embedded"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
