stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo build
    - cargo test

coverage:
  stage: build
  image: rust:latest
  before_script:
    - rustup component add rustfmt
    - cargo install cargo-kcov
    - apt-get update
    - apt-get install -y cmake g++ pkg-config jq
    - apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
    - cargo kcov --print-install-kcov-sh | sh
  script:
    - CARGO_TARGET_DIR=target/kcov cargo kcov --verbose --lib -- --verify --exclude-pattern=/home/user/.cargo,/usr/include,/usr/src/debug,src/util/loopback.rs,src/util/functional_test_util.rs
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
