[package]
name = "lightning-signer"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"

[lib]
name = "lightning_signer"
path = "src/lib.rs"

[dependencies]
backtrace = "0.3"
bitcoin = "0.24"
secp256k1 = { version="0.18.0", features = ["recovery"] }
bitcoin_hashes = "0.8.0"
hex = "0.3.2"
rand = "0.4"
tonic = "0.1.1"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
rust-crypto = "0.2.36"
bech32 = "0.7"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"

[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "9c9c88147e6a8fa637dc048f764ab8ecfea200d4"
[dev-dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "9c9c88147e6a8fa637dc048f764ab8ecfea200d4"
features = ["unsafe_revoked_tx_signing", "_test_utils"]

[dev-dependencies.bitcoin]
version = "0.24"
features = ["bitcoinconsensus"]

[dev-dependencies.bitcoinconsensus]
version = "0.19.0-1"

[build-dependencies]
tonic-build = "0.1.0"

[[bin]]
name = "client"
path = "src/client_main.rs"

[[bin]]
name = "server"
path = "src/server_main.rs"
