[package]
name = "lightning-signer"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"

[features]
default = ["grpc"]
grpc = ["tokio", "tonic", "prost", "serde", "serde_json", "clap"]

[lib]
name = "lightning_signer"
path = "src/lib.rs"

[dependencies]
backtrace = "0.3"
bitcoin = "0.24"
secp256k1 = { version = "0.18.0", features = ["recovery"] }
bitcoin_hashes = "0.8.0"
hex = "0.3.2"
rand = "0.4"
rust-crypto = "0.2.36"
bech32 = "0.7"
tonic = { version = "0.1.1", optional = true }
prost = { version = "0.6", optional = true }
tokio = { version = "0.2", features = ["macros"], optional = true }
serde = { version = "1.0.105", features = ["derive"], optional = true }
serde_json = { version = "1.0.48", optional = true }
clap = { version = "3.0.0-beta.2", optional = true }

[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "f151c029756622d06303252f918fce1b26809d23"
[dev-dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "f151c029756622d06303252f918fce1b26809d23"
features = ["unsafe_revoked_tx_signing", "_test_utils"]

[dev-dependencies.bitcoin]
version = "0.24"
features = ["bitcoinconsensus"]

[dev-dependencies.bitcoinconsensus]
version = "0.19.0-1"

[build-dependencies]
tonic-build = "0.1.0"

[[bin]]
name = "client"
path = "src/client_main.rs"
required-features = ["grpc"]

[[bin]]
name = "server"
path = "src/server_main.rs"
required-features = ["grpc"]
