[package]
name = "lightning-signer"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>"]
edition = "2018"

[lib]
name = "lightning_signer"
path = "src/lib.rs"

[dependencies]
backtrace = "0.3"
bitcoin = "0.23"
bitcoin_hashes = "0.7.6"
secp256k1 = { version="0.17.2", features = ["recovery"] }
hex = "0.3"
rand = "0.4"
tonic = "0.1.1"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
rust-crypto = "0.2.36"
bech32 = "0.7"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"

[dependencies.lightning]
git = "https://github.com/lightning-signer/rust-lightning.git"
rev = "4136c0e7822a07ff8acd0386c7fb58b369cb51f3"  # compat5 branch

[dev-dependencies.lightning]
git = "https://github.com/lightning-signer/rust-lightning.git"
rev = "4136c0e7822a07ff8acd0386c7fb58b369cb51f3"  # compat5 branch
features = ["unsafe"]

[dev-dependencies.bitcoin]
version = "0.23"
features = ["bitcoinconsensus"]

[build-dependencies]
tonic-build = "0.1.0"

[[bin]]
name = "client"
path = "src/client_main.rs"

[[bin]]
name = "server"
path = "src/server_main.rs"
