[package]
name = "lightning-signer"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>"]
edition = "2018"

[lib]
name = "lightning_signer"
path = "src/lib.rs"

[dependencies]
backtrace = "0.3"
bitcoin = "0.21"
bitcoin_hashes = "0.7"
secp256k1 = "0.15"
hex = "0.3"
rand = "0.4"
tonic = "0.1.1"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
rust-crypto = "0.2.36"
bech32 = "0.7"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"

[dependencies.lightning]
git = "https://github.com/lightning-signer/rust-lightning.git"
rev = "89d2b80b739987a674b5871589aa35001ecc4ee4"  # compat branch

[dev-dependencies.bitcoin]
version = "0.21"
features = ["bitcoinconsensus"]

[build-dependencies]
tonic-build = "0.1.0"

[[bin]]
name = "client"
path = "src/client_main.rs"

[[bin]]
name = "server"
path = "src/server_main.rs"
