[package]
name = "lightning-signer"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"

[features]
default = ["grpc", "persist_kv_json"]
grpc = ["tokio", "tonic", "prost", "serde", "serde_json", "clap"]
persist_kv_json = [ "kv", "serde_with", "secp256k1/serde" ]

[lib]
name = "lightning_signer"
path = "src/lib.rs"

[dependencies]
backtrace = "0.3"
bitcoin = "0.24"
secp256k1 = { version = "0.18.0", features = ["recovery"] }
bitcoin_hashes = "0.8.0"
hex = "0.3.2"
rand = "0.4"
rust-crypto = "0.2.36"
bech32 = "0.7"
kv = { version = "0.22.0", features = ["json-value"], optional = true }
tonic = { version = "0.1.1", optional = true }
prost = { version = "0.6", optional = true }
tokio = { version = "0.2", features = ["macros"], optional = true }
serde = { version = "1.0.105", features = ["derive"], optional = true }
serde_json = { version = "1.0.48", optional = true }
serde_with = { version = "1.6.4", features = ["hex"], optional = true }
clap = { version = "3.0.0-beta.2", optional = true }

[dev-dependencies]
tempfile = "3.2.0"

[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "94bb0c9128c2635ea08ec089f79fab04880dedd0"
[dev-dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "94bb0c9128c2635ea08ec089f79fab04880dedd0"
features = ["unsafe_revoked_tx_signing", "_test_utils"]

[dev-dependencies.bitcoin]
version = "0.24"
features = ["bitcoinconsensus"]

[dev-dependencies.bitcoinconsensus]
version = "0.19.0-1"

[build-dependencies]
tonic-build = "0.1.0"

[[bin]]
name = "client"
path = "src/client_main.rs"
required-features = ["grpc"]

[[bin]]
name = "server"
path = "src/server_main.rs"
required-features = ["grpc"]

[[bin]]
name = "persist_test"
path = "src/persist_test_main.rs"
required-features = ["persist_kv_json"]
