[package]
name = "vls-signer-stm32"
version = "0.1.0"
authors = ["Ken Sedgwick <ken@bonsai.com>", "Devrandom <c1.devrandom@niftybox.net>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
display-interface = { version = "0.4.1", optional = true }
stm32f4 = "0.14.0"
embedded-graphics = "0.7.1"
panic-semihosting = "0.5.3"
st7789 = "0.6.1"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
heapless = "0.7.5"

[dependencies.stm32f4xx-hal]
version = "0.13"
features = ["fsmc_lcd", "fsmc"]

[features]
stm32f412 = ["stm32f4xx-hal/stm32f412"]
stm32f413 = ["stm32f4xx-hal/stm32f413"]

[[bin]]
name = "demo_signer"
path = "src/demo_signer_main.rs"
