[package]
name = "vls-persist"
version = "0.1.0"
edition = "2018"

[lib]
name = "vls_persist"
path = "src/lib.rs"

[features]
default = ["std"]
std = ["lightning-signer-core/std", "log/std"]
no-std = ["lightning-signer-core/no-std"]
test_utils = ["lightning-signer-core/test_utils"]
kv-json = ["kv"]

[dependencies]
lightning-signer-core = { path = "../lightning-signer-core", default-features = false, features = ["serde"] }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_with = { version = "2.0", features = ["hex"] }
hex = { version = "0.4", default-features = false }
kv = { version = "0.22", features = ["json-value"], optional = true }
log = { version = "0.4", default-features = false }

[dev-dependencies]
tempfile = "3.2"
test-log = "0.2"
env_logger = "0.9"

[[bin]]
name = "persist_test"
path = "src/persist_test_main.rs"
required-features = ["kv-json", "test_utils"]
