[package]
name = "lightning-signer-server"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"

[features]
default = ["grpc", "persist_kv_json"]
grpc = ["tokio", "tonic", "prost", "serde", "serde_json", "clap", "lightning-signer-core/grpc"]
persist_kv_json = [ "kv", "serde_with", "bitcoin/use-serde" ]

[lib]
name = "lightning_signer_server"
path = "src/lib.rs"

[dependencies]
lightning-signer-core = { path = "../lightning-signer-core", features = ["debug"] }
backtrace = "0.3"
bip39 = {version = "1.0.0", features = ["rand"] }
hex = "0.3.2"
rand = "0.4"
kv = { version = "0.22.0", features = ["json-value"], optional = true }
tonic = { version = "0.1.1", optional = true }
prost = { version = "0.6", optional = true }
tokio = { version = "0.2", features = ["macros"], optional = true }
serde = { version = "1.0.105", features = ["derive"], optional = true }
serde_json = { version = "1.0.48", optional = true }
serde_with = { version = "1.6.4", features = ["hex"], optional = true }
clap = { version = "3.0.0-beta.2", optional = true }
bitcoin = { version = "0.26", features = ["bitcoinconsensus"]}

[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "3b67be235a46d8f9a9a6faf7ca7c5872ffbd8646"

# we need this for integration testing
features = ["unsafe_revoked_tx_signing", "_test_utils"]

[dev-dependencies]
tempfile = "3.2.0"

[build-dependencies]
tonic-build = "0.1.0"

[[bin]]
name = "client"
path = "src/client_main.rs"
required-features = ["grpc"]

[[bin]]
name = "server"
path = "src/server_main.rs"
required-features = ["grpc"]

[[bin]]
name = "persist_test"
path = "src/persist_test_main.rs"
required-features = ["persist_kv_json"]
