[package]
name = "secp256k1-xonly"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.27", default_features = false, features = ["no-std"] }
