[package]
name = "vls-proxy"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>"]
edition = "2018"
build = "build.rs"

[features]

default = ["grpc"]
grpc = ["tokio", "tonic", "prost"]

[dependencies]
lightning-signer-core = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "3778a66e3c969041e7bcc530e63e6b822a802f72" }
vls-protocol-signer = { path = "../vls-protocol-signer" }
secp256k1 = { version = "0.20", features = ["rand-std", "bitcoin_hashes"] }
nix = "0.22"
serde = "1.0"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4"
# .4 doesn't compile with 1.45.2
clap = "=3.0.0-beta.2"
clap_derive = "=3.0.0-beta.5"
# 0.2.5 doesn't compile with 1.45.2
http = "=0.2.4"
# 1.17 pulls in parking-lot-core which doesn't compile with 1.48.0
tokio = { version = "=1.16.1", features = ["macros", "rt-multi-thread"], optional = true }
tokio-stream = "0.1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = "0.14"
tonic = { version = "0.6.2", optional = true }
prost = { version = "0.9.0", optional = true }
ctrlc = { version = "3.1", features = ["termination"] }
triggered = "0.1"
async-stream = "0.3"

[dependencies.lightning-signer-server]
git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git"
rev = "3778a66e3c969041e7bcc530e63e6b822a802f72"
default_features = false
features = ["persist_kv_json"]

[build-dependencies]
tonic-build = "0.6.2"

[lib]
name = "vls_proxy"
path = "src/lib.rs"

[[bin]]
# A single-binary drop-in replacement for hsmd
name = "remote_hsmd_vls"
path = "src/vls_main.rs"

[[bin]]
# A single-binary two-process replacement for hsmd, communicating over a gRPC connection
name = "remote_hsmd_vls_grpc2"
path = "src/grpc_main.rs"
required-features = ["grpc"]
