[package]
name = "lightning-storage-server"
version = "0.1.0"
edition = "2018"

[lib]
name = "lightning_storage_server"
path = "src/lib.rs"

[dependencies]
sled = "0.34"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"

[dev-dependencies]
tempfile = "3"
