[package]
name = "lightning-signer-core"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"

[features]

# just so that `cargo test` runs the functional test by default, but you can disable this
default = ["test_utils"]

# if you use tonic, this is convenient for auto-conversion of MySigner Status to tonic::Status
grpc = ["tonic"]

test_utils = ["lightning/_test_utils", "lightning/unsafe_revoked_tx_signing"]

[lib]
name = "lightning_signer"
path = "src/lib.rs"

[dependencies]
hex = "0.3.2"

# TODO make optional
# for creating a new channel
rand = "0.4"
# for c-lightning compatibility (hkdf), but should be able to use relevant bits from bitcoin crate
rust-crypto = "0.2.36"
backtrace = "0.3"
# TODO end

tonic = { version = "0.1.1", optional = true }

[dev-dependencies]
tempfile = "3.2.0"

[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "95779285575d3139482a73a943234c7dd82eb956"

[dev-dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "95779285575d3139482a73a943234c7dd82eb956"
features = ["_test_utils"]

[dependencies.bitcoin]
version = "0.26"
# we need this for integration testing
features = ["bitcoinconsensus"]

[dev-dependencies.bitcoinconsensus]
version = "0.19.0-3"

[[bin]]
name = "example_main"
path = "src/example_main.rs"

[[test]]
name = "functional_test"
path = "tests/functional_test.rs"
required-features = ["test_utils"]
