[package]
name = "lightning-signer-core"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"

[features]

# just so that `cargo test` runs the functional test by default, but you can disable this
default = ["test_utils"]

# if you use tonic, this is convenient for auto-conversion of MySigner Status to tonic::Status
grpc = ["tonic"]

test_utils = ["lightning/_test_utils", "lightning/unsafe_revoked_tx_signing"]

[lib]
name = "lightning_signer"
path = "src/lib.rs"

[dependencies]
# Also depended by rust-lightning
hex = "0.3.2"

# TODO make optional
# for creating a new channel
rand = "0.4"
backtrace = { version = "0.3", optional = true }
# TODO end

tonic = { version = "0.1.1", optional = true }

[dev-dependencies]
tempfile = "3.2.0"

[dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "3b67be235a46d8f9a9a6faf7ca7c5872ffbd8646"

[dev-dependencies.lightning]
git = "https://github.com/rust-bitcoin/rust-lightning.git"
rev = "3b67be235a46d8f9a9a6faf7ca7c5872ffbd8646"
features = ["_test_utils"]

[dependencies.bitcoin]
version = "0.26"
# we need this for integration testing
features = ["bitcoinconsensus"]

[dev-dependencies.bitcoinconsensus]
version = "0.19.0-3"

[[bin]]
name = "example_main"
path = "src/example_main.rs"

[[test]]
name = "functional_test"
path = "tests/functional_test.rs"
required-features = ["test_utils"]
