[package]
name = "greenlight-protocol"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_bolt = { version = "0.1" }

[dev-dependencies]
regex = "1.5"
hex = "0.4"
